# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: servidor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'servidor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservidor.proto\"*\n\x0bUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\":\n\x07Service\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\")\n\x0bServiceList\x12\x1a\n\x08services\x18\x01 \x03(\x0b\x32\x08.Service\"#\n\x0bTaxiRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x1d\n\x0cTaxiResponse\x12\r\n\x05plate\x18\x01 \x01(\t2\x95\x01\n\rMyUberService\x12/\n\x0cRegisterUser\x12\x0c.UserRequest\x1a\x11.RegisterResponse\x12\'\n\x0fGetServiceTypes\x12\x06.Empty\x1a\x0c.ServiceList\x12*\n\x0bRequestTaxi\x12\x0c.TaxiRequest\x1a\r.TaxiResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servidor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=18
  _globals['_USERREQUEST']._serialized_end=60
  _globals['_REGISTERRESPONSE']._serialized_start=62
  _globals['_REGISTERRESPONSE']._serialized_end=114
  _globals['_EMPTY']._serialized_start=116
  _globals['_EMPTY']._serialized_end=123
  _globals['_SERVICE']._serialized_start=125
  _globals['_SERVICE']._serialized_end=183
  _globals['_SERVICELIST']._serialized_start=185
  _globals['_SERVICELIST']._serialized_end=226
  _globals['_TAXIREQUEST']._serialized_start=228
  _globals['_TAXIREQUEST']._serialized_end=263
  _globals['_TAXIRESPONSE']._serialized_start=265
  _globals['_TAXIRESPONSE']._serialized_end=294
  _globals['_MYUBERSERVICE']._serialized_start=297
  _globals['_MYUBERSERVICE']._serialized_end=446
# @@protoc_insertion_point(module_scope)
